trigger:
- master

pool:
  vmImage: 'macOS-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
    checkLatest: true

- script: |
    npm install -g @ionic/cli
    npm install
  displayName: 'Install dependencies'

- script: |
    ionic build
  displayName: 'Build Ionic App'

# Add additional steps for testing, code signing, etc. as needed.

# Example: Deploy to Firebase Hosting
# - task: FirebaseDeploy@0
#   inputs:
#     action: 'deploy'
#     projectId: '<your-firebase-project-id>'
#     token: '$(FIREBASE_AUTH_TOKEN)'
#   displayName: 'Deploy to Firebase Hosting'
